### ISSUE TITLE
Hunspell 1.3.2 contractions issues

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#205]
Hunspell 1.3.2 appears to have issues parsing some contractions even though they're in the dictionary.

---------
[root@letni /]# egrep "wouldn't|can't" en_US.dic 
can't
wouldn't
[root@letni /]# echo "can't"|hunspell
Hunspell 1.3.2
*
*

[root@letni /]# echo "wouldn't"|hunspell
Hunspell 1.3.2
& wouldn 3 0: would, woulds, would n
*

[root@letni /]#

Original comment by: mtwomey

Original Ticket: [hunspell/bugs/222](https://sourceforge.net/p/hunspell/bugs/222)

**Comment by sooheon** [comment]
@phajdan it looks like the linked dictionary is quite small, and not as up to date as the SCOWL official dictionaries. With the SCOWL dictionaries, contractions are pretty inconsistent with "can't" being recognized, but "wouldn't" or "you've" not being recognized. There must be some kind of bug because all of these contractions exist in the actual .dic file.
