### ISSUE TITLE
Initial caps and long-S (U+017E)

### ISSUE THREAD

**Issue by BongoVR** [hunspell/hunspell#365]
Hello,
I am trying to create a spellchecker for a Fraktur compatible variant of German. This means that the initial s-letter, among others, has to be a long-S (U+017E). Everything works now except for one detail. Words starting with a long-S will not be recognised when at the beginning of a sentence, hence "ſo" which becomes "So" will not match.
I have digged in the source code and tracked the issue down to Hunspell::analyze:

case INITCAP: there is a call to mkallsmall (thus transforming "So" to "so") follwing by a mkinitcap call. Then, both results are searched in the dictionary.
The unicode character tables (chapchars_utf and the like) are OK, they provide "S" as the corresponding capital letter for "ſ".

I have not found a way to tell Hunspell in the affix file to always try to match a "S" to "ſ" instead of "s" when it is at the beginning of a word.

Can somebody imagine a solution to this problem?

**Comment by srtxg** [comment]
The problem is that the case conversion is not a bijection.
You can convert fro small long s to uppercase "S"; but "S" only converts to lowercase "s".
A similar thing happens with greek final sigma (however that one is only capitalized on all capps words).

I tested, and indeed hunspell doesn't recognizes ΠΑΥΛΟΣ as an all caps form of Παυλος

A dirty but easy fix would be to duplicate all dictionnary entries staring with "ſ" as starting with "S", and use a nossugest flag.
eg in *.aff file:
NOSUGGEST X

and add flag "X" to all entries starting with "X".

I tested and seems to work:
test.aff
SET UTF-8
NOSUGGEST X
test.dic
ſoso
Soso/X

test file:
Sozo -> suggests Soso
Soso -> accepted ok
soso -> suggests ſoso
sozo -> suggests ſoso

**Comment by BongoVR** [comment]
Thank you for taking the time to look into the issue.
I was actually doing what you suggest and duplicated all lower-case entries. However, I did not include the NOSUGGEST flag; it already seems to work as expected. On the other hand, it is important to remember to remove all prefix flags for the copied upper-case items - only suffix flags are needed.

**Comment by PanderMusubi** [comment]
If this question has been answered satisfactory, can this issue be closed?
