### ISSUE TITLE
Provided dictionaries are not listed as available

### ISSUE THREAD

**Issue by odonyde** [hunspell/hunspell#440]
The issue:
Hunspell 1.5.4 does not list the provided dictionaries as available and therefore Atom package "linter-spell" (https://github.com/yitzchak/linter-spell) believes that no dictionaries are available.

The details:

- I have compiled Hunspell 1.5.4 with the "--with-ui" switch via MSYS2/MinGW-W64 for my Windows 10 64bit system and copied the executable (hunspell.exe) and the required libraries (libgcc_s_seh-1.dll, libhunspell-1.5-0.dll, libiconv-2.dll, libintl-8.dll, libstdc++-6.dll, libwinpthread-1.dll) to folder "C:\Hunspell".
- I have copied dictionary files for American English (en_US.aff, en_US.dic) and Brazilian Portuguese (pt_BR.aff, pt_BR.dic) to "C:\Hunspell\dict".
- I have added "C:\Hunspell" to environment variable PATH and set DICPATH to "C:\Hunspell\dict" and DICTIONARY to "en_US,pt_BR".
- Running Hunspell on a text file via "hunspell C:\Hunspell\test.txt" works fine and catches and corrects both English and Portuguese spelling mistakes (see screenshot).
![hunspell_test](https://cloud.githubusercontent.com/assets/21695902/20970755/0d5028be-bc76-11e6-86b1-7b9f2aa6c6a8.jpg)
- Executing "hunspell -D" shows the configured dictionary folder as first search path but does not list the provided dictionaries as available and only shows the American English dictionary as loaded (see screenshot).
![hunspell_availabledictionaries](https://cloud.githubusercontent.com/assets/21695902/20970457/de097ff2-bc74-11e6-8576-58c7bcfbe43d.jpg)

The question:
What do I need to do to let Hunspell pick up and list the provided dictionaries as available?

**Comment by dimztimz** [comment]
They should be listed under AVAILABLE DICTIONARIES. But that feature works only on POSIX operating systems because we use OS function calls to enumerate the directory, and we have only done that for POSIX APIs.

You can probably get that stuff in Windows with MingW since MINGW provides some posix functionality with this patch https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-hunspell/0005-windows-sub-dicts-paths.patch which, so far, is not applied in upstream.

You can try and see if that patch fixes things on windows. If everything works then you can also make pull request.

**Comment by odonyde** [comment]
Hi Dimitrij,

Your hint was spot on! Incorporating Alexey's patch from https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-hunspell/0005-windows-sub-dicts-paths.patch solved the issue and all provided dictionaries are correctly listed as available also on my Windows 10 system now (see screenshot).

![hunspell_availabledictionaries_02](https://cloud.githubusercontent.com/assets/21695902/20986700/d75bec80-bcb0-11e6-9cf8-b55b2879aa8f.jpg)

Thanks for your support! As suggested I have created a pull request #441 to incorporate the changes into Hunspell's master branch.
